# Local stand-in for "Terraform wrote an inventory Ansible can read."
# No AWS account. Run from this directory: terraform init && terraform apply

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

variable "fake_host" {
  type        = string
  default     = "10.0.0.10"
  description = "Pretend this is the public IP Terraform would have created."
}

resource "local_file" "ansible_inventory" {
  filename = "${path.module}/inventory.ini"
  content  = <<-EOT
    # Generated by Terraform local-lab. Not a real host.
    [web]
    ${var.fake_host}
  EOT
}

output "inventory_path" {
  value = local_file.ansible_inventory.filename
}
